### ISSUE TITLE
How to remove a preference from a PreferenceGroup?

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone#95]
```
EditTextPreference userid = (EditTextPreference) account.getPreference(1);
    	userid.getEditText().setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);
		userid.setOnPreferenceChangeListener(useridChangedListener);
		if (!isNewAccount){
			userid.setText(mPrefs.getAccountUserId(n));
			userid.setSummary(userid.getText());
		}
```	
I tried to hide a preference, by calling:

`account.removePreference(userid);`

but the app will crash when I open an Account Preference screen.

and getting this error
```
Process: org.linphone, PID: 21883
    java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.get(ArrayList.java:411)
        at android.preference.PreferenceGroup.getPreference(PreferenceGroup.java:123)
        at org.linphone.AccountPreferencesFragment.initAccountPreferencesFields(AccountPreferencesFragment.java:316)
        at org.linphone.AccountPreferencesFragment.onCreate(AccountPreferencesFragment.java:69)
        at android.app.Fragment.performCreate(Fragment.java:2336)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
        at android.app.BackStackRecord.setLastIn(BackStackRecord.java:860)
        at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:900)
        at android.app.BackStackRecord.run(BackStackRecord.java:728)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
        at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
        at org.linphone.LinphoneActivity.changeFragment(LinphoneActivity.java:505)
        at org.linphone.LinphoneActivity.changeCurrentFragment(LinphoneActivity.java:460)
        at org.linphone.LinphoneActivity.changeCurrentFragment(LinphoneActivity.java:380)
        at org.linphone.LinphoneActivity.displayAccountSettings(LinphoneActivity.java:850)
        at org.linphone.LinphoneActivity$9.onClick(LinphoneActivity.java:1621)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

Could you give me a hint?

**Comment by Miteshmakwana73** [comment]
changing index help me to solve issue 
`mProxyPreference = (EditTextPreference) advanced.getPreference(1);`
